# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('menu', '0004_order_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='creation_time',
            field=models.DateTimeField(),
        ),
    ]
