# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 17:52
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField()),
                ('delivery_time', models.DateTimeField()),
                ('pickup_loc', models.CharField(max_length=64)),
                ('code_word', models.CharField(max_length=32)),
                ('timeliness', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('friendliness', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('responsetime', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('text_feedback', models.CharField(max_length=140)),
                ('delivers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivers', to=settings.AUTH_USER_MODEL)),
                ('initiates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
